### PR TITLE
Bracket Expansion

### PR DESCRIPTION
**Pull request by graphemecluster**
Requested feature by Henry

### CODE REVIEW

**Review by ayaka14732 — APPROVED** [review]

**Comment by hfhchan** [comment]
I don't know python, but if you tested it and it works then go ahead
Btw which syntax did we settle on in the end?

**Comment by graphemecluster** [comment]
@hfhchan
```
[乒砰𠹶][鈴呤][嘭𠾴]唥,ping1 ling1 paang1 laang1|bing4 ling1 baang4 laang4
```
This will generate all 3 × 2 × 2 × 2 = 24 cases

This also works:
```
花園,faa1 jyun[24]
```

Note that don't do
```
借花[敬獻]佛,ze3 faa1 (ging3|hin3) fat6
```
as 4 entries will be generated.

**Comment by graphemecluster** [comment]
And note the difference between `圓(碌碌|轆轆),jyun4 luk1 luk1` and `圓[碌轆][碌轆],jyun4 luk1 luk1` as the former will cause 2 entries being generated while the latter being 4.

**Comment by graphemecluster** [comment]
As for punctuation expansion,

```
一分耕耘，一分收穫,jat1 fan1 gaang1 wan4 jat1 fan1 sau1 wok6
```

will generate 3 entries and 

```
行得正，[企徛]得正，唔怕雷公喺天頂,haang4 dak1 zeng3 kei5 dak1 zeng3 m4 paa3 leoi4 gung1 hai2 tin1 deng2
```

will generate 5 entries:

```
行得正
企得正
徛得正
唔怕雷公喺天頂
行得正，企得正，唔怕雷公喺天頂
行得正，徛得正，唔怕雷公喺天頂
```

(but not `行得正，企得正` and `行得正，徛得正` as some AAA parallelisms present)

**Pull request merged**
