### PR TITLE
Initialize enwiktionary script

### PR DESCRIPTION
**Pull request by szc126**
See #88.

### CODE REVIEW

**Review by tanxpyox — APPROVED** [review]
Note: requires conversion to OpenCC standard + sanitisation

**Comment by tanxpyox** [comment]
closes #88

**Comment by sgalal** [comment]
license 點處理？

**Comment by laubonghaudoi** [comment]
@szc126 你引入嘅呢啲數據係咩 license 嘅？

**Comment by szc126** [comment]
"Text is available under the [Creative Commons Attribution-ShareAlike License](https://creativecommons.org/licenses/by-sa/3.0/)".

**Comment by sgalal** [comment]
CC BY-SA 同我哋嘅 CC BY 有衝突，可能要分成單獨嘅檔案，用單獨嘅 license

**Comment by tanxpyox** [comment]
好似之前open street map 嗰嗰寫法？

**Comment by ayaka14732** [comment]
> 好似之前open street map 嗰嗰寫法？

我自己嘅專案係噉做嘅：[ayaka14732/rime-putonghua](https://github.com/ayaka14732/rime-putonghua)

即係將 `LICENSE` 檔拆做兩個，分別係 `LICENSE-CC-BY` 同埋 `LICENSE-CC-BY-SA`，跟住喺 README 入邊説明邊啲檔案用邊個 license

**Pull request merged**
