### PR TITLE
Fix reverse lookup of words

### PR DESCRIPTION
**Pull request by ayaka14732**
Currently, when using _Putonghua_ _pinyin_ (普通話拼音) to reverse lookup ni (你), there is a comment of its Cantonese pronunciation nei5. However, for words over one characters, like ni hao (你好), there is no comment of its Cantonese pronunciation. This is a known issue of librime: https://github.com/rime/home/issues/500.

This pull request proposes a method that enables words over one characters to have comments when doing the reverse lookup by creating a new dictionary called `jyut6ping3_unspaced`. The file is automatically generated from `jyut6ping3` by running the Python script `tools/build_unspaced.py`. The difference is that all the spaces are replaced by equal signs (`=`).

The drawback of this method is that the dictionary will be stored twice in the repository. However, considering the benefits it provides, this change can be quite worthwhile.

### CODE REVIEW

**Comment by tanxpyox** [comment]
LGTM! - but if it makes the installer too big, I think a better way of doing it is incorporating the builder script to the CI workflow, so that we can keep this unspaced branch updated and usable as an optional module.

**Comment by LEOYoon-Tsaw** [comment]
I'd really hope that someone fix it in librime rather than creating a duplicated dictionary for length>1 words. But I have to admit this works for now.

**Comment by tanxpyox** [comment]
> 合併落master嘞

我都係覺得將呢個功能分開做另一個branch好啲——如果唔係個安裝包會有成40MB.... 加上已經寫好晒自動生成嘅script，應該可以用 Github Actions 實裝 (trigger on commit)

**Comment by laubonghaudoi** [comment]
如果係噉嘅話，噉安裝教程嗰度要加多一個部分教點樣裝呢個branch

**Comment by laubonghaudoi** [comment]
@ayaka14732 我係唔係可以先閂咗呢個 PR？

**Pull request closed without merging**
