### PR TITLE
Update jyut6ping3.schema.yaml

### PR DESCRIPTION
**Pull request by weakish**
More relaxed pronounciation rules.

Reference:

https://zh-yue.wikipedia.org/wiki/粵語懶音#例子

### CODE REVIEW

**Comment by graphemecluster** [comment]
These sound changes are not accepted by LSHK. See https://www.cuhk.edu.hk/ics/clrc/crcl_102_1/lshk.pdf

**Comment by laubonghaudoi** [comment]
呢個變動嘅意思係將「如果」發成「如古」都接受埋？

**Comment by weakish** [comment]
> These sound changes are not accepted by LSHK.

These are commented out (disabled) by default.

>  呢個變動嘅意思係將「如果」發成「如古」都接受埋

係呀。不過呢個變動收緊咗，之前「瓜」發成「家」都得。

**Comment by laubonghaudoi** [comment]
既然唔係默認打開嘅，噉都可以接受啦

**Pull request merged**
